PARAGRAPHS = [
    "He had three simple rules by which he lived. The first was to never eat blue food. There was nothing in nature that was edible that was blue. People often asked about blueberries, but everyone knows those are actually purple. He understood it was one of the stranger rules to live by, but it had served him well thus far in the 50+ years of his life.",
    "The morning sun rose slowly over the quiet valley, casting a soft golden light across the wide fields and the ancient trees. Birds began to sing their early songs, filling the crisp air with sweet music that echoed through the hills. A gentle breeze moved through the long green grass, making it ripple like the waves of a calm blue ocean. In the middle of this peaceful landscape sat a small wooden house with a red roof and clean windows. A narrow stone path wound its way from the wooden front door down to a small, clear stream that bubbled happily over smooth grey rocks.",
    "Inside the house, a young man named Leo was busy preparing his breakfast. He boiled water for tea, sliced fresh bread, and spread sweet strawberry jam over it. He always enjoyed these early hours of the day because the world felt completely still and free from worry. He took his warm cup and his plate outside, sitting down on a comfortable wooden bench near the garden. His small black dog, Max, ran over and sat right next to his feet, hoping for a tiny piece of bread. Leo smiled and gave the dog a small crumb, then looked out at the beautiful view before him.",
    "Every day followed a simple routine here, but he never grew tired of it. After finishing his breakfast, he walked down to the edge of the water to wash his cup. The water was cold and refreshing, coming straight from the high mountains that stood far away in the distance. These mountains were always covered in white snow, even during the warmest months of the summer. They looked like giant guardians watching over the peaceful valley below.",
    "Leo decided it was a perfect day for a long walk into the nearby forest to gather dry wood for his fireplace. He put on his sturdy brown boots, grabbed a strong canvas bag, and called out to his dog. Max barked with joy and ran ahead, his tail wagging quickly with excitement. They walked past the garden, crossed the little wooden bridge over the stream, and entered the shade of the tall trees.",
    "The forest was full of life, yet it felt wonderfully calm. Big green leaves formed a thick canopy overhead, allowing only small beams of sunlight to touch the ground. Squirrels jumped quickly from branch to branch, while small rabbits hid behind the bushes as Leo and Max walked past. Leo took deep breaths of the clean air, which smelled of damp earth and fresh pine. He stopped every few steps to pick up pieces of dry wood that had fallen from the branches during the last wind storm.",
    "Leo sat down on a large smooth stone near the tree to rest his legs for a moment. Max sat down beside him, panting softly and looking around the beautiful clearing. Leo thought about his life in the valley and felt deep gratitude for the peace he enjoyed every single day. He remembered living in a large, noisy city many years ago, where cars were always honking, people were always rushing, and the air was filled with grey smoke. Moving to this quiet valley was the best decision he had ever made, as it allowed him to connect with nature and find true happiness in simple things.",
    "Leo cooked a simple dinner, ate it by the warm light of the fire, and felt completely relaxed. He knew that tomorrow would bring the exact same routine, but he looked forward to it with a happy heart. The world outside was vast and full of changes, but inside his quiet valley, life remained beautiful, peaceful, and delightfully simple. He finally closed his book, put out the fire, and went to sleep as the stars began to shine brightly in the dark night sky."
]
